00:39:54 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:40:59 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:42:52 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:40:31 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:40:56 - main - ERROR - <module>: 219 - A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: too many messages to send as an album
Traceback (most recent call last):
  File "/home/runner/work/FortDaily-PVE_bot/FortDaily-PVE_bot/main.py", line 216, in <module>
    sending()
  File "/home/runner/work/FortDaily-PVE_bot/FortDaily-PVE_bot/main.py", line 185, in sending
    bot.send_media_group(chat_id=channel_id, media=mediagroup)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/telebot/__init__.py", line 2523, in send_media_group
    result = apihelper.send_media_group(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/telebot/apihelper.py", line 516, in send_media_group
    return _make_request(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/telebot/apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/telebot/apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: too many messages to send as an album
00:43:00 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:37:36 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:44:02 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:42:48 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:39:56 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:37:57 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:39:28 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:40:23 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:37:27 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:37:27 - main - ERROR - <module>: 219 - cannot write empty image as JPEG
Traceback (most recent call last):
  File "/home/runner/work/FortDaily-PVE_bot/FortDaily-PVE_bot/main.py", line 216, in <module>
    sending()
  File "/home/runner/work/FortDaily-PVE_bot/FortDaily-PVE_bot/main.py", line 184, in sending
    mediagroup = [telebot.types.InputMediaPhoto(i) for i in daily_shop()]
  File "/home/runner/work/FortDaily-PVE_bot/FortDaily-PVE_bot/main.py", line 184, in <listcomp>
    mediagroup = [telebot.types.InputMediaPhoto(i) for i in daily_shop()]
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/telebot/types.py", line 6222, in __init__
    media = service_utils.pil_image_to_file(media)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/telebot/service_utils.py", line 62, in pil_image_to_file
    image.convert('RGB').save(photoBuffer, extension, quality=quality)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/PIL/Image.py", line 2432, in save
    save_handler(self, fp, filename)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 637, in _save
    raise ValueError(msg)
ValueError: cannot write empty image as JPEG
