00:31:37 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:29:37 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:31:08 - main - WARNING - <module>: 18 - ________________________________HELLO__________________________________
00:31:17 - main - WARNING - sending: 194 - cannot write empty image as JPEG
00:31:26 - main - ERROR - <module>: 234 - cannot write empty image as JPEG
Traceback (most recent call last):
  File "/home/runner/work/FortDaily-PVE_bot/FortDaily-PVE_bot/main.py", line 187, in sending
    mediagroup = [telebot.types.InputMediaPhoto(i) for i in mediaphoto_jpeg_skins]
  File "/home/runner/work/FortDaily-PVE_bot/FortDaily-PVE_bot/main.py", line 187, in <listcomp>
    mediagroup = [telebot.types.InputMediaPhoto(i) for i in mediaphoto_jpeg_skins]
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/telebot/types.py", line 6222, in __init__
    media = service_utils.pil_image_to_file(media)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/telebot/service_utils.py", line 62, in pil_image_to_file
    image.convert('RGB').save(photoBuffer, extension, quality=quality)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/PIL/Image.py", line 2432, in save
    save_handler(self, fp, filename)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 637, in _save
    raise ValueError(msg)
ValueError: cannot write empty image as JPEG

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/FortDaily-PVE_bot/FortDaily-PVE_bot/main.py", line 232, in <module>
    sending()
  File "/home/runner/work/FortDaily-PVE_bot/FortDaily-PVE_bot/main.py", line 197, in sending
    mediagroup = [telebot.types.InputMediaPhoto(i) for i in mediaphoto_jpeg_skins]
  File "/home/runner/work/FortDaily-PVE_bot/FortDaily-PVE_bot/main.py", line 197, in <listcomp>
    mediagroup = [telebot.types.InputMediaPhoto(i) for i in mediaphoto_jpeg_skins]
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/telebot/types.py", line 6222, in __init__
    media = service_utils.pil_image_to_file(media)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/telebot/service_utils.py", line 62, in pil_image_to_file
    image.convert('RGB').save(photoBuffer, extension, quality=quality)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/PIL/Image.py", line 2432, in save
    save_handler(self, fp, filename)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/PIL/JpegImagePlugin.py", line 637, in _save
    raise ValueError(msg)
ValueError: cannot write empty image as JPEG
